# Generated by Django 5.2.3 on 2025-06-28 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the checklist item', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item', null=True)),
                ('procedure', models.TextField(blank=True, help_text='Steps or script for completing this checklist item', null=True)),
            ],
            options={
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the department', null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Unique hostname of the machine', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the machine', null=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp of the last check-in from the agent')),
                ('overall_status', models.CharField(choices=[('PENDING', 'Pending Setup'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PENDING', help_text='Overall preparation status of the machine', max_length=20)),
                ('is_lead', models.BooleanField(default=False, help_text='Is this machine assigned to a team lead?')),
                ('department', models.ForeignKey(blank=True, help_text='Department this machine belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='systemPrepApp.department')),
            ],
            options={
                'verbose_name_plural': 'Machines',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the productivity tool', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the tool', null=True)),
                ('install_command', models.TextField(blank=True, help_text='Command or script content for installation', null=True)),
                ('optional', models.BooleanField(default=False, help_text='Is this tool optional for a department?')),
                ('departments', models.ManyToManyField(blank=True, related_name='productivity_tools', to='systemPrepApp.department')),
            ],
            options={
                'verbose_name_plural': 'Productivity Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', help_text='Status of this specific checklist item', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any notes or error messages for this item', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemPrepApp.checklistitem')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to='systemPrepApp.machine')),
            ],
            options={
                'verbose_name_plural': 'Machine Checklist Statuses',
                'unique_together': {('machine', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='MachineToolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_INSTALLED', 'Not Installed'), ('IN_PROGRESS', 'In Progress'), ('INSTALLED', 'Installed'), ('FAILED', 'Failed')], default='NOT_INSTALLED', help_text='Installation status of this specific tool', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any notes or error messages for this tool', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_statuses', to='systemPrepApp.machine')),
                ('productivity_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemPrepApp.productivitytool')),
            ],
            options={
                'verbose_name_plural': 'Machine Tool Statuses',
                'unique_together': {('machine', 'productivity_tool')},
            },
        ),
    ]
