# Generated by Django 5.2.3 on 2025-06-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemPrepApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='optional_tools',
            field=models.ManyToManyField(blank=True, help_text='Optional tools specifically assigned to this machine.', related_name='machines_with_optional_assignment', to='systemPrepApp.productivitytool'),
        ),
    ]
