# Generated by Django 5.2.3 on 2025-06-28 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemPrepApp', '0002_machine_optional_tools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Checklist Item', 'verbose_name_plural': 'Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['hostname'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='machinecheckliststatus',
            options={'ordering': ['checklist_item__order'], 'verbose_name': 'Machine Checklist Status', 'verbose_name_plural': 'Machine Checklist Statuses'},
        ),
        migrations.AlterModelOptions(
            name='machinetoolstatus',
            options={'verbose_name': 'Machine Tool Status', 'verbose_name_plural': 'Machine Tool Statuses'},
        ),
        migrations.AlterModelOptions(
            name='productivitytool',
            options={'ordering': ['name'], 'verbose_name': 'Productivity Tool', 'verbose_name_plural': 'Productivity Tools'},
        ),
        migrations.RenameField(
            model_name='machinetoolstatus',
            old_name='productivity_tool',
            new_name='tool',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_seen',
        ),
        migrations.AlterUniqueTogether(
            name='machinetoolstatus',
            unique_together={('machine', 'tool')},
        ),
        migrations.RemoveField(
            model_name='productivitytool',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='productivitytool',
            name='install_command',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Is this a critical item for deployment?'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this item should appear.'),
        ),
        migrations.AddField(
            model_name='department',
            name='productivity_tools',
            field=models.ManyToManyField(blank=True, help_text='Default productivity tools required for this department.', related_name='departments', to='systemPrepApp.productivitytool'),
        ),
        migrations.AddField(
            model_name='machine',
            name='checklist_items',
            field=models.ManyToManyField(blank=True, help_text='Checklist items associated with this machine and their status.', related_name='machines_with_status', through='systemPrepApp.MachineChecklistStatus', to='systemPrepApp.checklistitem'),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_checkin',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last check-in from the machine agent.'),
        ),
        migrations.AddField(
            model_name='machinetoolstatus',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productivitytool',
            name='download_link',
            field=models.URLField(blank=True, help_text='URL to download the tool installer.', null=True),
        ),
        migrations.AddField(
            model_name='productivitytool',
            name='version',
            field=models.CharField(blank=True, help_text='Current version of the tool.', max_length=50),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the checklist item.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='name',
            field=models.CharField(help_text="Name of the checklist item (e.g., 'Install Antivirus')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description of the department's role."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Name of the department (e.g., 'Engineering', 'Marketing')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this machine is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='systemPrepApp.department'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hostname',
            field=models.CharField(help_text='Network hostname of the machine.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the machine (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_lead',
            field=models.BooleanField(default=False, help_text="Is this machine designated as a 'lead' for a task or department?"),
        ),
        migrations.AlterField(
            model_name='machine',
            name='overall_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready for Deployment'), ('ERROR', 'Error')], default='PENDING', help_text='Overall preparation status of the machine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_statuses', to='systemPrepApp.checklistitem'),
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Any notes related to this item's status."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('N_A', 'Not Applicable')], default='PENDING', help_text='Current status of this checklist item for the machine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinetoolstatus',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemPrepApp.machine'),
        ),
        migrations.AlterField(
            model_name='machinetoolstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Installation'), ('INSTALLED', 'Installed'), ('FAILED', 'Installation Failed'), ('UNINSTALLED', 'Uninstalled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='productivitytool',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description or purpose of the tool.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productivitytool',
            name='name',
            field=models.CharField(help_text="Name of the productivity tool (e.g., 'Microsoft Office', 'VS Code')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productivitytool',
            name='optional',
            field=models.BooleanField(default=False, help_text='Is this tool optional, or is it a default requirement for specific departments?'),
        ),
        migrations.RemoveField(
            model_name='machinetoolstatus',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='machinetoolstatus',
            name='notes',
        ),
    ]
