# Generated by Django 5.2.3 on 2025-06-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemPrepApp', '0003_alter_checklistitem_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
