# Generated by Django 5.2.3 on 2025-06-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemPrepApp', '0004_machine_assigned_user_machine_assignment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstallationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='completed', max_length=50)),
                ('installed_tools', models.JSONField(blank=True, default=list)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_reports', to='systemPrepApp.machine')),
            ],
        ),
    ]
