# Generated by Django 5.2.3 on 2025-06-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemPrepApp', '0005_agentinstallationreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinecheckliststatus',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='machinecheckliststatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='machine',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemPrepApp.checklistitem'),
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='machinecheckliststatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('N_A', 'Not Applicable')], default='PENDING', max_length=20),
        ),
    ]
